-- Additive JobPush-ready schema extension.
--
-- Safe for the existing JobLens sponsorship flow:
--   * companies(fein) remains the primary key.
--   * existing columns read by backend/app/tools/entity_resolver.py are kept.
--   * new tables/columns are additive.

ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS company_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_company_id ON companies(company_id);
CREATE INDEX IF NOT EXISTS idx_companies_name ON companies(name);
CREATE INDEX IF NOT EXISTS idx_companies_state ON companies(state);
CREATE INDEX IF NOT EXISTS idx_companies_naics_code ON companies(naics_code);

CREATE TABLE IF NOT EXISTS company_groups (
    company_group_id BIGSERIAL PRIMARY KEY,
    group_key      TEXT NOT NULL UNIQUE,
    canonical_name TEXT NOT NULL,
    display_name   TEXT,
    notes          TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_company_groups_canonical_name
    ON company_groups(canonical_name);

CREATE TABLE IF NOT EXISTS company_group_companies (
    company_group_id BIGINT NOT NULL REFERENCES company_groups(company_group_id) ON DELETE CASCADE,
    fein             TEXT NOT NULL REFERENCES companies(fein) ON DELETE CASCADE,
    relationship     TEXT NOT NULL DEFAULT 'legal_entity',
    is_primary       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (company_group_id, fein)
);
CREATE INDEX IF NOT EXISTS idx_company_group_companies_fein
    ON company_group_companies(fein);
CREATE INDEX IF NOT EXISTS idx_company_group_companies_group
    ON company_group_companies(company_group_id);

CREATE TABLE IF NOT EXISTS company_websites (
    website_id       BIGSERIAL PRIMARY KEY,
    fein             TEXT REFERENCES companies(fein) ON DELETE CASCADE,
    company_group_id BIGINT REFERENCES company_groups(company_group_id) ON DELETE CASCADE,
    website_type     TEXT NOT NULL DEFAULT 'corporate',
    url              TEXT NOT NULL,
    normalized_domain TEXT,
    source           TEXT,
    status           TEXT NOT NULL DEFAULT 'unverified',
    notes            TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (fein IS NOT NULL OR company_group_id IS NOT NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_company_websites_unique_target_url
    ON company_websites(COALESCE(fein, ''), COALESCE(company_group_id, 0), url);
CREATE INDEX IF NOT EXISTS idx_company_websites_fein ON company_websites(fein);
CREATE INDEX IF NOT EXISTS idx_company_websites_group ON company_websites(company_group_id);
CREATE INDEX IF NOT EXISTS idx_company_websites_domain ON company_websites(normalized_domain);

CREATE TABLE IF NOT EXISTS lca_cases (
    lca_case_id BIGSERIAL PRIMARY KEY,
    source_snapshot TEXT NOT NULL,
    source_row_number INTEGER NOT NULL,
    case_number TEXT,
    case_status TEXT,
    received_date DATE,
    decision_date DATE,
    original_cert_date DATE,
    visa_class TEXT,
    job_title TEXT,
    soc_code TEXT,
    soc_title TEXT,
    full_time_position TEXT,
    begin_date DATE,
    end_date DATE,
    total_worker_positions INTEGER,
    new_employment INTEGER,
    continued_employment INTEGER,
    change_previous_employment INTEGER,
    new_concurrent_employment INTEGER,
    change_employer INTEGER,
    amended_petition INTEGER,
    employer_name TEXT,
    trade_name_dba TEXT,
    employer_city TEXT,
    employer_state TEXT,
    employer_postal_code TEXT,
    employer_country TEXT,
    employer_province TEXT,
    employer_phone TEXT,
    employer_phone_ext TEXT,
    employer_fein TEXT,
    naics_code TEXT,
    employer_poc_last_name TEXT,
    employer_poc_first_name TEXT,
    employer_poc_middle_name TEXT,
    employer_poc_job_title TEXT,
    employer_poc_city TEXT,
    employer_poc_state TEXT,
    employer_poc_postal_code TEXT,
    employer_poc_country TEXT,
    employer_poc_province TEXT,
    employer_poc_phone TEXT,
    employer_poc_phone_ext TEXT,
    employer_poc_email TEXT,
    worksite_workers INTEGER,
    secondary_entity TEXT,
    secondary_entity_business_name TEXT,
    worksite_city TEXT,
    worksite_county TEXT,
    worksite_state TEXT,
    worksite_postal_code TEXT,
    wage_rate_of_pay_from NUMERIC,
    wage_rate_of_pay_to NUMERIC,
    wage_unit_of_pay TEXT,
    prevailing_wage NUMERIC,
    pw_unit_of_pay TEXT,
    pw_tracking_number TEXT,
    pw_wage_level TEXT,
    pw_oes_year TEXT,
    pw_other_source TEXT,
    pw_other_year TEXT,
    pw_survey_publisher TEXT,
    pw_survey_name TEXT,
    total_worksite_locations INTEGER,
    agree_to_lc_statement TEXT,
    h_1b_dependent TEXT,
    willful_violator TEXT,
    support_h1b TEXT,
    statutory_basis TEXT,
    appendix_a_attached TEXT,
    public_disclosure TEXT,
    preparer_last_name TEXT,
    preparer_first_name TEXT,
    preparer_middle_initial TEXT,
    preparer_business_name TEXT,
    preparer_email TEXT,
    row_fingerprint TEXT NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_lca_cases_snapshot_row
    ON lca_cases(source_snapshot, source_row_number);
CREATE INDEX IF NOT EXISTS idx_lca_cases_case_number ON lca_cases(case_number);
CREATE INDEX IF NOT EXISTS idx_lca_cases_employer_fein ON lca_cases(employer_fein);
CREATE INDEX IF NOT EXISTS idx_lca_cases_employer_name ON lca_cases(employer_name);
CREATE INDEX IF NOT EXISTS idx_lca_cases_decision_date ON lca_cases(decision_date);
CREATE INDEX IF NOT EXISTS idx_lca_cases_job_title ON lca_cases(job_title);
CREATE INDEX IF NOT EXISTS idx_lca_cases_worksite_state ON lca_cases(worksite_state);
CREATE INDEX IF NOT EXISTS idx_lca_cases_row_fingerprint ON lca_cases(row_fingerprint);
