"""Tokens too common for single-word index keys or single-token fuzzy."""

GENERIC_TOKENS = frozenset(
    {
        "hiring",
        "staffing",
        "solutions",
        "services",
        "service",
        "consulting",
        "group",
        "partners",
        "partner",
        "global",
        "international",
        "systems",
        "industries",
        "industry",
        "technologies",
        "technology",
        "holdings",
        "enterprises",
        "enterprise",
        "associates",
        "management",
        "resources",
        "digital",
        "software",
        "company",
        "companies",
        "american",
        "gamma",
        "university",
        "united",
        "national",
        "advanced",
        "north",
        "south",
        "east",
        "west",
        "central",
        "community",
        "first",
        "general",
        "professional",
        "business",
        "world",
        "city",
        "state",
        "pacific",
        "atlantic",
        "prime",
        "blue",
        "green",
        "red",
        "new",
        "best",
        "all",
        "one",
    }
)

# Max employers sharing a short brand token before we skip indexing it.
MAX_SHORT_TOKEN_COLLISIONS = 5
